name: Deploy to AKS Prod

on:
  push:
    branches:
      - main
    paths:
      - 'remix-weather-app/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials (prod)
        run: |
          az aks get-credentials \
            --name ${{ secrets.AKS_CLUSTER_PROD }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --overwrite-existing

      - name: Apply deployment and service manifests
        run: |
          kubectl apply -f k8s-app-deployment/

      - name: Update image and rollout
        env:
          ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
          SHA: ${{ github.sha }}
        run: |
          echo "Updating image to ${ACR_NAME}.azurecr.io/remix-weather:${SHA}"
          kubectl set image deployment/remix-weather remix-weather=${ACR_NAME}.azurecr.io/remix-weather:${SHA}
          kubectl rollout status deployment remix-weather
