name: Terraform Static Checks
 
on:
  push:
    paths:
      - 'terraform/**'
 
jobs:
  static-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
 
      - name: Terraform FMT Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Validate
        run: terraform validate
 
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working-directory: terraform