name: Terraform Plan
 
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
 
jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
 
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v1
 
      - name: Run tflint
        run: tflint
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"