name: Terraform Static Checks
 
on:

  push:

    paths:

      - 'terraform/**'
 
jobs:

  static-checks:

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: terraform
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3

        with:

          terraform_version: 1.6.6
 
      - name: Azure Login via OIDC

        uses: azure/login@v1

        with:

          client-id: ${{ secrets.AZURE_CLIENT_ID }}

          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      - name: Terraform FMT Check

        run: terraform fmt -check -recursive
 
      - name: Terraform Init (for validation)

        run: terraform init

        env:

          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

          ARM_USE_OIDC: true
 
      - name: Terraform Validate

        run: terraform validate
 
      - name: Run tfsec

        uses: aquasecurity/tfsec-action@v1.0.0

        with:

          working-directory: terraform

 